project:
  type: book

lang: es

book:
  title: "Álgebra Lineal Numérica Para Aprendizaje Estadístico"
  subtitle: "Notas de Estudio"
  author: "Miguel Trias"
  date: "4/1/2026"
  license: "CC BY-NC-SA"
  repo-url: https://github.com/mtrias/alnae
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - file: intro.qmd
      text: Introducción
    - file: clase-2.qmd
      text: Clase 2
    - file: clase-3.qmd
      text: Clase 3 ~18/3
    - file: clase-4.qmd
      text: Clase 4 ~20/3
    - file: clase-5.qmd
      text: Clase 5 ~25/3
    - file: clase-6.qmd
      text: Clase 6 ~27/3
    - file: clase-7.qmd
      text: Clase 7 ~8/4
    - file: clase-7-bis.qmd
      text: Clase 7 Bis
    - file: clase-8.qmd
      text: Clase 8 ~17/4
  appendices:
    - file: strang-gauss-lu.qmd
    - file: strang-def-pos.qmd
    - file: strang-svd.qmd
    - references.qmd

bibliography: references.bib
csl: https://www.zotero.org/styles/apa

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    math: mathjax
    number-sections: false
    anchor-sections: true
    smooth-scroll: true
    include-after-body: toggle-citations.html


