project:
  type: book

lang: es

book:
  title: "Álgebra Lineal Numérica Para Aprendizaje Estadístico"
  subtitle: "Notas de Estudio del Curso 2026"
  author:
    name: "Miguel Trias"
    affiliations:
        - name: "Udelar"
          department: "Facultad de Ciencias Económicas y Administración"
          city: "Montevideo"
          country: "Uruguay"
  date: last-modified
  license: "CC BY-NC-SA"
  abstract: |
    Éste libro compila el material de estudio del curso Álgebra Lineal Para Aprendizaje Estadístico del año 2026.
    Está basado en los apuntes de clase del Profesor Diego Armentano y en las cátedras del Profesor Gilbert Strang.
  description: "Libro sobre álgebra lineal computacional"
  keyword: "Álgebra Lineal, SVD, Machine Learning, FCEA, ALNAE, Aprendizaje Estadístico, Álgebra Matricial"
  repo-url: https://github.com/mtrias/alnae
  repo-actions: [edit, issue]
  downloads: [pdf]
  chapters:
    - index.qmd
    - file: intro.qmd
    - file: clase-01.qmd
    - file: clase-02.qmd
    - file: clase-03.qmd
    - file: clase-04.qmd
    - file: clase-05.qmd
    - file: clase-06.qmd
    - file: clase-07.qmd
    - file: clase-08.qmd
    - file: clase-09.qmd
    - file: clase-10.qmd
  appendices:
    - file: apx-espectro-matrices-aleatorias.qmd
    - file: apx-gauss-lu.qmd
    - file: apx-diagonalizacion.qmd
    - file: apx-sintesis.qmd
  references: references.qmd

bibliography: references.bib
#csl: https://www.zotero.org/styles/apa

toc: true
number-sections: true
number-depth: 2

format:
  html:
    theme:
      light: cosmo
      dark: darkly
      #light: flatly
      #light: journal
      #light: lumen
      #light: Yeti
      #light: Zephyr
      #light: united
      #light: spacelab
      #light: sandstone
      #light: simplex
    respect-user-color-scheme: true
    css: styles.css
    math: mathjax
    anchor-sections: true
    smooth-scroll: true
    include-after-body: toggle-citations.html
  pdf:
      documentclass: scrreprt
      output-file: "alnae-2026.pdf"

